[package]
name = "notem"
description = "A simple note taking command line tool"
version = "0.1.0"
authors = ["Daniel Paz-Soldan <daniel.pazsoldan@gmail.com>"]
license = "MIT"

[dependencies]
chrono = "0.4"
which = "1.0"
